ALTER TABLE `mt_goods`
  ADD COLUMN `COST_PRICE` DECIMAL (10, 2) DEFAULT 0.00 NULL COMMENT '成本价格' AFTER `LINE_PRICE`;

ALTER TABLE `mt_goods_sku`
  ADD COLUMN `COST_PRICE` DECIMAL (10, 2) DEFAULT 0.00 NULL COMMENT '成本价格' AFTER `LINE_PRICE`;