ALTER TABLE `mt_merchant`
    ADD COLUMN `START_TIME` datetime DEFAULT NULL COMMENT '有效期开始时间' AFTER `UPDATE_TIME`,
    ADD COLUMN `END_TIME` datetime DEFAULT NULL COMMENT '有效期结束时间' AFTER `START_TIME`;
