ALTER TABLE `mt_merchant`
ADD COLUMN `SETTLE_RATE` DECIMAL NULL COMMENT '结算比例' AFTER `WX_OFFICIAL_APP_SECRET`;

ALTER TABLE `mt_settlement`
ADD COLUMN `SETTLE_RATE` DECIMAL NULL COMMENT '结算比例' AFTER `STORE_ID`;