ALTER TABLE `mt_order`
  ADD COLUMN `CONFIRM_STATUS` CHAR (1) DEFAULT 'N' NULL COMMENT '核销状态' AFTER `STAFF_ID`,
  ADD COLUMN `CONFIRM_TIME` DATETIME NULL COMMENT '核销时间' AFTER `CONFIRM_STATUS`,
  ADD COLUMN `CONFIRM_REMARK` VARCHAR (500) NULL COMMENT '核销备注' AFTER `CONFIRM_TIME`;